TRADING_PAIRS = [
    'BTC/USDT', 'ETH/USDT', 'BNB/USDT', 'XRP/USDT',
    'SOL/USDT', 'PEPE/USDT', 'SUI/USDT', 'WIF/USDT', 'DOGE/USDT'
]

TIMEFRAMES = ['1m', '15m', '1h', '1d']

# Indicator parameters
DEFAULT_ATR_PERIOD = 10
DEFAULT_RSI_PERIOD = 14
DEFAULT_EMA_PERIOD = 10

# TP/SL parameters
DEFAULT_TP_PERCENT = 1.0
DEFAULT_SL_PERCENT = 0.5
DEFAULT_ATR_MULTIPLIER = 2.0

# Trading parameters
RSI_OVERSOLD = 50
RSI_OVERBOUGHT = 50
INITIAL_BALANCE = 100.0
POSITION_SIZE = 50
RISK_PER_TRADE = 2.0
